### ISSUE TITLE
non si visualizza l'elenco delle risorse sul sito http://petrusino.opendatasicilia.it/

### ISSUE THREAD

**Issue by cirospat** [SiciliaHub/petrusino#8]
da oggi ho notato che non si visualizza l'elenco delle risorse su http://petrusino.opendatasicilia.it/.
Stessa cosa per i vari accussi.opendatasicilia.it, pnrr.opendatasicilia.it e vari progetti costruiti alla stessa maniera.

Questo è il file di Google spreadsheet che alimenta il catalogo Petrusino sull'interfaccia di SIMILE EXHIBIT:
https://docs.google.com/spreadsheets/d/1H38J-cLEAt8VhDuhMvJgSGH4KzT0LrhFl9tvGTQpqWI/edit#gid=0
Credo che il problema stia in questo link.

Sul file `index.html` questa è l'istruzione per far visualizzare l'elenco delle risorse sull'interfaccia SIMILE EXHIBIT:
```
<link rel="exhibit/data" 
    type="application/jsonp"
    href="https://spreadsheets.google.com/feeds/list/1H38J-cLEAt8VhDuhMvJgSGH4KzT0LrhFl9tvGTQpqWI/od6/public/basic?alt=json-in-script"
    ex:converter="googleSpreadsheets" />
```

Se clicco su
[https://spreadsheets.google.com/feeds/list/1H38J-cLEAt8VhDuhMvJgSGH4KzT0LrhFl9tvGTQpqWI/od6/public/basic?alt=json-in-script](https://spreadsheets.google.com/feeds/list/1H38J-cLEAt8VhDuhMvJgSGH4KzT0LrhFl9tvGTQpqWI/od6/public/basic?alt=json-in-script)
non si apre nulla quindi non esiste più una fonte dati da cui attingere per la visualizzazione delle risorse censite sul Google spreadsheet.

Se puoi dare un occhiata @aborruso  please

**Comment by aborruso** [comment]
@cirospat si può cambiare il tipo di source in CSV, che come output funziona.

Me l'assegno e con calma risolvo

**Comment by cirospat** [comment]
grazie @aborruso
studierò la tua soluzione perchè abbiamo creato tanti progetti con questa
soluzione e dobbiamo aggiornarli tutti.

**Comment by cirospat** [comment]
ciao @aborruso 
quando è possibile aspetto la soluzione al problema.
Lo scrivo solo perchè ho diversi progetti (di cui 2 per lavoro) strutturati allo stesso modo che non funzionano.
Grazie sempre...

**Comment by aborruso** [comment]
caro @cirospat entro fine mese faccio il test del passaggio a CSV secco. Spero di trovare il tempo e la lucidità.

Sappi che sono certo che funzionerà, mi sono documentato.

**Comment by cirospat** [comment]
> caro @cirospat entro fine mese faccio il test del passaggio a CSV secco. Spero di trovare il tempo e la lucidità.
> Sappi che sono certo che funzionerà, mi sono documentato.

Grazie sempre :)

**Comment by cirospat** [comment]
@aborruso 
ho studiato (ricerche su Google)
**[ti ho seguito](https://groups.google.com/g/simile-widgets/c/0MacjGasLFU)**
ho smanettato (ore di prove)  :)
e l'ho trovato (la solution al problemone)!!!

**NON SI USA PIU' QUESTA IMPOSTAZIONE NEL FILE `INDEX.HTML`**:
```
<link rel="exhibit/data" 
    type="application/jsonp"
    href="https://spreadsheets.google.com/feeds/list/1jM0kzFXTEsMkuhCl6NW8WsHMlSRvf71yV4y3jPIuXxw/od6/public/basic?alt=json-in-script"
    ex:converter="googleSpreadsheets" />
```

**ORA SI USA QUESTA**:

```
<link rel="exhibit/data" 
    type="text/csv"
    href="https://docs.google.com/spreadsheets/d/e/2PACX-1vSiXsVGzwQ1gc7l9zSs5GffY4iWC55maUfHRZJiBHwJxA2YSUi3IS11oFfmF2lYPqjGOOrC8MIFKwYe/pub?output=csv"     />
```

dove
il link di href è l'**output CSV del Google spreadsheet**.
In pratica SIMILE EXHIBIT funziona non solo con file JSON ma anche con file CSV. Quindi basta dare le giuste istruzioni al file `index.html`.


### Ma non basta, bisogna fare altre 2 cose

**1° azione**:
Nel Google spreadsheet alla colonna "**`url`**" non bisogna più inserire le parentesi graffe `{`url`}` nel titolo intestazione campo.

**2° azione**:
Nel file **`index.html`** del progetto su Github bisogna eliminare le due partesti graffe `{{ }}` da url
    prima era così:
    <td><a ex:href-content=".url" ex:onclick-subcontent="trackOutboundLink('`{{.url}}`') ......
    che diventa così ora:
    <td><a ex:href-content=".url" ex:onclick-subcontent="trackOutboundLink('`.url`') ......

**Test**
Ho provato le nuove impostazioni con un mio recente progetto https://cirospat.github.io/pnrr_2021_opendata/ e funziona come prima.


Sono contento di avere trovato la soluzione ma ti ho seguito come un segugio. Lo spingitore sei stato tu, io ho avuto solo "buon" fiuto. Ho lavorato sulle dritte fornite da chi ha interagito con te sul forum https://groups.google.com/g/simile-widgets/c/0MacjGasLFU  ma le parentesi graffe sono farina del mio sacco :)

Questa issue è importante da far conoscere a chi usa Simile Exhibit (es. Gianni Vitrano, G.ppe Ragusa, ..).

Quando puoi valida questa procedura e poi chiudiamo felicemente l'issue :)

**Comment by cirospat** [comment]
resta un problema:
le celle (sul Google spreadsheet) in cui due entità erano separati da **`;`** ora sono attaccati sull'interfaccia di Simile Exhibit.
![image](https://user-images.githubusercontent.com/3757525/131094714-1976e873-7008-402d-922e-e58a1d7c00cf.png)

Anche inserendo l'istruzione:
`data-ex-value-separator=";"`
non funziona

E' un problema da risolvere

**Comment by gbvitrano** [comment]
io in palermohub ho il problema con il codice html 

`<img src="legend/clip_index/valutazioni_ambientali.jpg" class="clip_tooltips"  />`

viene riscritta cosi

`<img src="legend/clip_index/valutazioni_ambientali.jpg" "="" class="" clip_tooltips""="">`

**Comment by gbvitrano** [comment]
> data-ex-value-separator=";"

se non ho capito male, questo parametro specifica inizio e fine della colonna nel csv
Ora sto riorganizzando la home di palermohub, parte di codice adesso viene renderizzato male

**Comment by cirospat** [comment]
ho apportato le modifiche al file index.html di **Petrusino** secondo quanto riportato nel [commento sopra](https://github.com/SiciliaHub/petrusino/issues/8#issuecomment-906577377).
E ora funziona = http://petrusino.opendatasicilia.it

Inoltre ho tolto gli apici prima e dopo .URL ([al rigo 183 del codice](https://github.com/SiciliaHub/petrusino/blob/ba9a805016566d110fcfa716bafbd88925f4e2fc/index.html#L183))
`<td><a ex:href-content=".URL" ex:onclick-subcontent="trackOutboundLink(.URL); return false;" target="_blank"><strong><span ex:content=".titolo" class="accussì"></strong></span></a></td>`
perchè altrimenti cliccando sul link non riporta all'URL della risorsa esterna.

Rimane solo da risolvere il problema di cui al [commento](https://github.com/SiciliaHub/petrusino/issues/8#issuecomment-906634846) = 2 o più tag separati da **`;`** non vengono renderizzati come tag separati sull'interfaccia Simile Exhibit, ma vengono uniti come fossero un unico tag

**Comment by aborruso** [comment]
Ciao @cirospat tutto risolto, devi aggiungere questa istruzione:

https://github.com/SiciliaHub/petrusino/blob/gh-pages/index.html#L47

Come separatore dei tag, usa la `,`.

Baci

**Comment by UO-TransizioneDigitaleComunePalermo** [comment]
> Come separatore dei tag, usa la `,`.

Grazie @aborruso 
quindi domande:

1. nello spreadsheet Google devo usare la `,` al posto del `;` ?
2. nello spreadsheet devo continuare a non lasciare spazi tra un tag ed un altro (es.:  `ambiente,energia`)

Grazie :)

**Comment by aborruso** [comment]
Sì e sì

**Comment by cirospat** [comment]
> Sì e sì

grazie, vado a modificare :)

**Comment by cirospat** [comment]
> https://github.com/SiciliaHub/petrusino/blob/gh-pages/index.html#L47
> Come separatore dei tag, usa la `,`.

sperimentando ho capito che la virgola `,` non può essere usata nei campi in cui c'è una descrizione da fare. 
Nel caso di Petrusino nel database
(https://docs.google.com/spreadsheets/d/1H38J-cLEAt8VhDuhMvJgSGH4KzT0LrhFl9tvGTQpqWI/edit#gid=0)
la `,`  non può essere usata nei campi:

- **label**
- **descrizione**

![image](https://user-images.githubusercontent.com/3757525/132945062-0e0e8ad7-badf-4f77-96ca-599ca43897c8.png)

altrimenti ci ritroviamo a leggere "and" nei rispettivi campi.

Quindi immagino che si possa usare un altro simbolo al posto della `,`  come ad esempio trattino `-`  oppure altro `|`

**Comment by aborruso** [comment]
Ok USA il "|"

E devi modificare anche nel codice html in quella parte che ho inserito

**Comment by cirospat** [comment]
> Ok USA il "|"

d'accordo. 


> E devi modificare anche nel codice html in quella parte che ho inserito

Già fatto =  `ex:valueSeparator=","`

**Comment by aborruso** [comment]
Ciro li nel codice gli devi dire che il data separator è il "|" e non la virgola

**Comment by aborruso** [comment]
Ovvero

ex:valueSeparator="|"

**Comment by cirospat** [comment]
> Ovvero
> 
> ex:valueSeparator="|"

grazie, così si risolve il problema,
sono stupido a non averci pensato!

**Comment by aborruso** [comment]
@cirospat se è tutto ok, per favore chiudila.

Grazie

**Comment by cirospat** [comment]
Riepilogo le soluzioni individuate con questa issue. 

**1**
**Codice per fare leggere i dati dallo spreadsheet Google da inserire nel file `index.html`:**
```
<link rel="exhibit/data"
    ex:valueSeparator="|"
    type="text/csv"
    href="https://docs.google.com/spreadsheets/d/e/2PACX-1vRMGF9LE7_T9LNFKAZnjCSZz5E1pNvjue9MOz1VwexsqgzcgLIxYAU0dkCciSZpy9J8-sGMt2lxnqEe/pub?output=csv"     />
```
dove `|` è il separatore dei valori contenuti dentro una cella dello spreadsheet

**2**
**Togliere le parentesi graffe `{ }` dalla denominazione campi del Google spreadsheet**

**3**
**Nel file `index.html` del progetto su Github bisogna eliminare le due parentesi graffe `{{ }}` da url**
prima era così:
`<a ex:href-content=".url" ex:onclick-subcontent="trackOutboundLink('{{.url}}') ......`
che diventa così ora:
`<a ex:href-content=".url" ex:onclick-subcontent="trackOutboundLink('.url') ......`

**4**
**togliere gli apici prima e dopo `.URL` ([al rigo 185 del codice](https://github.com/SiciliaHub/petrusino/blob/5543a22646edf644baf198f0aa79fc74b6effd15/index.html#L185
))**
`<td><a ex:href-content=".URL" ex:onclick-subcontent="trackOutboundLink(.URL); return false;" target="_blank"><strong><span ex:content=".titolo" class="accussì"></strong></span></a></td>`   

perchè altrimenti nell'interfaccia di Simile Exhibit cliccando sul link non riporta all'URL della risorsa esterna.

---

E chiuso issue.
Grazie @aborruso per il tuo tempo!
